'use client';
import { useEffect, useState } from 'react';
import { Loader2, Save, Star, Trash2, X } from 'lucide-react';
type Category = { id: string; name: string };
type Image = { id?: string; url: string; publicId?: string | null; primary?: boolean };
type Product = { id: string; name: string; brand: string | null; description: string | null; categoryId: string; active: boolean; featured: boolean; images?: Image[] };
type Props = { product?: Product | null; onClose: () => void; onSaved: () => void };
type Form = { name: string; brand: string; description: string; categoryId: string; active: boolean; featured: boolean };
const empty: Form = { name: '', brand: '', description: '', categoryId: '', active: true, featured: false };

export function AdminProductForm({ product, onClose, onSaved }: Props) {
  const [categories, setCategories] = useState<Category[]>([]); const [form, setForm] = useState<Form>(empty); const [files, setFiles] = useState<File[]>([]); const [images, setImages] = useState<Image[]>(product?.images || []); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/categories').then(async r => { if (r.ok) setCategories(await r.json()); }).catch(() => setError('Não foi possível carregar as categorias.')); }, []);
  useEffect(() => { setForm(product ? { name: product.name, brand: product.brand || '', description: product.description || '', categoryId: product.categoryId, active: product.active, featured: product.featured } : empty); setImages(product?.images || []); setFiles([]); }, [product]);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(old => ({ ...old, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (!form.name.trim() || !form.categoryId) return setError('Nome e categoria são obrigatórios.'); setSaving(true); try { const response = await fetch(product ? `/api/products/${product.id}` : '/api/products', { method: product ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível salvar o produto.'); for (const file of files) { const body = new FormData(); body.append('file', file); body.append('productId', data.id); const upload = await fetch('/api/uploads', { method: 'POST', body }); const uploaded = await upload.json(); if (!upload.ok) throw new Error(uploaded.error || 'Falha no upload.'); const attach = await fetch(`/api/products/${data.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: uploaded.url, publicId: uploaded.publicId, alt: form.name }) }); if (!attach.ok) throw new Error('Falha ao associar imagem.'); } onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro ao salvar o produto.'); } finally { setSaving(false); } }
  async function removeImage(image: Image) { if (!product?.id || !image.id || !window.confirm('Excluir esta imagem?')) return; const response = await fetch(`/api/products/${product.id}/images/${image.id}`, { method: 'DELETE' }); if (!response.ok) return setError('Não foi possível excluir a imagem.'); setImages(old => old.filter(item => item.id !== image.id)); }
  async function makePrimary(image: Image) { if (!product?.id || !image.id) return; const response = await fetch(`/api/products/${product.id}/images/${image.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ primary: true }) }); if (response.ok) setImages(old => old.map(item => ({ ...item, primary: item.id === image.id }))); }
  return <div className="admin-modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="admin-modal"><div className="admin-modal-header"><div><span className="section-kicker">Catálogo</span><h2>{product ? 'Editar produto' : 'Novo produto'}</h2><p>Informações e imagens do produto.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X size={19} /></button></div><form onSubmit={submit} className="admin-form">{error && <div className="admin-form-error">{error}</div>}<div className="admin-form-grid"><label><span>Nome *</span><input required value={form.name} onChange={e => update('name', e.target.value)} /></label><label><span>Marca</span><input value={form.brand} onChange={e => update('brand', e.target.value)} /></label></div><label><span>Categoria *</span><select required value={form.categoryId} onChange={e => update('categoryId', e.target.value)}><option value="">Selecione</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span>Descrição</span><textarea rows={4} value={form.description} onChange={e => update('description', e.target.value)} /></label><label><span>Adicionar imagens</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => setFiles(Array.from(e.target.files || []))} /><small>JPG, PNG ou WEBP, até 5 MB por arquivo.</small></label>{product && images.length > 0 && <div className="image-upload-preview">{images.map(image => <div className={image.primary ? 'product-image-item primary' : 'product-image-item'} key={image.id}><img src={image.url} alt={form.name} /><button type="button" onClick={() => makePrimary(image)} aria-label="Definir como imagem principal"><Star size={15} fill={image.primary ? 'currentColor' : 'none'} /></button><button type="button" onClick={() => removeImage(image)} aria-label="Excluir imagem"><Trash2 size={15} /></button></div>)}</div>}<div className="admin-checkbox-grid"><label className="admin-checkbox"><input type="checkbox" checked={form.active} onChange={e => update('active', e.target.checked)} /><span><strong>Produto ativo</strong><small>Visível no catálogo público.</small></span></label><label className="admin-checkbox"><input type="checkbox" checked={form.featured} onChange={e => update('featured', e.target.checked)} /><span><strong>Produto em destaque</strong><small>Usado na página inicial.</small></span></label></div><div className="admin-modal-footer"><button type="button" className="secondary-button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? <><Loader2 size={17} className="spin" /> Salvando...</> : <><Save size={17} /> Salvar produto</>}</button></div></form></div></div>;
}
